SELECT * FROM BOOK WHERE PRICE LIKE '' ORDER BY NO ASC;

SELECT * FROM BOOK WHERE BRWDAY LIKE '%17/12/20 22:49%' ORDER BY NO ASC;

-- int, Integer (INT)
SELECT * FROM BOOK WHERE PRICE = 35000 ORDER BY NO ASC;
SELECT * FROM BOOK WHERE PRICE = 111 ORDER BY NO ASC;
SELECT * FROM BOOK WHERE PRICE = -1 ORDER BY NO ASC;

SELECT * FROM BOOK WHERE PRICE > -1 ORDER BY NO ASC;
SELECT * FROM BOOK WHERE PRICE >= -1 ORDER BY NO ASC;

SELECT * FROM BOOK WHERE PRICE < 34999 ORDER BY NO ASC;
SELECT * FROM BOOK WHERE PRICE <= 35000 ORDER BY NO ASC;

SELECT * FROM BOOK WHERE 110 < PRICE AND PRICE < 35001 ORDER BY NO ASC;
SELECT * FROM BOOK WHERE -1 <= PRICE AND PRICE <= 34999 ORDER BY NO ASC;
--------------------------------------------------------------------------------



-- Date (LocalDate)
SELECT * FROM BOOK WHERE PERIOD = '2017-12-16' ORDER BY NO ASC;
SELECT * FROM BOOK WHERE PERIOD BETWEEN '2017-12-16' AND '2017-12-18' ORDER BY NO ASC;  -- 해당 기간의 모든 데이터
SELECT * FROM BOOK WHERE PERIOD BETWEEN '2017-12-16' AND '2017-12-16' ORDER BY NO ASC;  -- 해당 일의 모든 데이터
SELECT * FROM BOOK WHERE PERIOD BETWEEN '2017-12-01' AND '2017-12-31' ORDER BY NO ASC;  -- 해당 월의 모든 데이터
SELECT * FROM BOOK WHERE PERIOD BETWEEN '2017-01-01' AND '2017-12-31' ORDER BY NO ASC;  -- 해당 년의 모든 데이터
--------------------------------------------------------------------------------

