--------------------------------------------------------
--  파일이 생성됨 - 토요일-12월-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEST_TABLE
--------------------------------------------------------

  CREATE TABLE "HBM"."TEST_TABLE" 
   (	"NO" NUMBER, 
	"DATA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HBM.TEST_TABLE
SET DEFINE OFF;
Insert into HBM.TEST_TABLE (NO,DATA) values (1,'data1');
Insert into HBM.TEST_TABLE (NO,DATA) values (2,'data2');
--------------------------------------------------------
--  DDL for Index TEST_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HBM"."TEST_TABLE_PK" ON "HBM"."TEST_TABLE" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TEST_TABLE
--------------------------------------------------------

  ALTER TABLE "HBM"."TEST_TABLE" ADD CONSTRAINT "TEST_TABLE_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HBM"."TEST_TABLE" MODIFY ("NO" NOT NULL ENABLE);
