--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VISITOR
--------------------------------------------------------

  CREATE TABLE "HBM"."VISITOR" 
   (	"NO" NUMBER, 
	"GRADE" CHAR(1 BYTE), 
	"ID" VARCHAR2(40 BYTE), 
	"PW" VARCHAR2(60 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"BIRTH" CHAR(6 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"PHONE" CHAR(9 BYTE), 
	"IMGFILE" VARCHAR2(60 BYTE), 
	"HPHONE" CHAR(10 BYTE), 
	"ADDR" VARCHAR2(100 BYTE), 
	"COMP" VARCHAR2(60 BYTE), 
	"POS" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HBM.VISITOR
SET DEFINE OFF;
Insert into HBM.VISITOR (NO,GRADE,ID,PW,NAME,BIRTH,EMAIL,PHONE,IMGFILE,HPHONE,ADDR,COMP,POS) values (17,'3','test2','4567','박영희','930920','test@gmail.com','04567890 ','pyh.jpg','515017619 ','부산시 남구 대연동','부경대학교','컴퓨터공학과');
Insert into HBM.VISITOR (NO,GRADE,ID,PW,NAME,BIRTH,EMAIL,PHONE,IMGFILE,HPHONE,ADDR,COMP,POS) values (19,'3','test2','4567','박영희','930920','test@gmail.com','04567890 ','pyh.jpg','515017619 ','부산시 남구 대연동','부경대학교','컴퓨터공학과');
Insert into HBM.VISITOR (NO,GRADE,ID,PW,NAME,BIRTH,EMAIL,PHONE,IMGFILE,HPHONE,ADDR,COMP,POS) values (12,'3','test2','4567','박영희','930920','test@gmail.com','04567890 ','pyh.jpg','515017619 ','부산시 남구 대연동','부경대학교','컴퓨터공학과');
Insert into HBM.VISITOR (NO,GRADE,ID,PW,NAME,BIRTH,EMAIL,PHONE,IMGFILE,HPHONE,ADDR,COMP,POS) values (21,'3','test2','4567','박영희','930920','test@gmail.com','04567890 ','pyh.jpg','515017619 ','부산시 남구 대연동','부경대학교','컴퓨터공학과');
Insert into HBM.VISITOR (NO,GRADE,ID,PW,NAME,BIRTH,EMAIL,PHONE,IMGFILE,HPHONE,ADDR,COMP,POS) values (16,'5','test1','1234','김철수','910301','test@naver.com','012345678','kcs.jpg','515027916 ','부산시 사상구 모라동','집','집');
Insert into HBM.VISITOR (NO,GRADE,ID,PW,NAME,BIRTH,EMAIL,PHONE,IMGFILE,HPHONE,ADDR,COMP,POS) values (18,'3','test1','1234','김철수','910301','test@naver.com','012345678',null,'0000000000',null,null,null);
Insert into HBM.VISITOR (NO,GRADE,ID,PW,NAME,BIRTH,EMAIL,PHONE,IMGFILE,HPHONE,ADDR,COMP,POS) values (20,'3','test1','1234','김철수','910301','test@naver.com','012345678',null,'0000000000',null,null,null);
Insert into HBM.VISITOR (NO,GRADE,ID,PW,NAME,BIRTH,EMAIL,PHONE,IMGFILE,HPHONE,ADDR,COMP,POS) values (11,'3','test1','1234','김철수','910301','test@naver.com','012345678',null,'0000000000',null,null,null);
Insert into HBM.VISITOR (NO,GRADE,ID,PW,NAME,BIRTH,EMAIL,PHONE,IMGFILE,HPHONE,ADDR,COMP,POS) values (13,'3','test1','1234','김철수','910301','test@naver.com','012345678',null,'0000000000',null,null,null);
--------------------------------------------------------
--  DDL for Index VISITOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HBM"."VISITOR_PK" ON "HBM"."VISITOR" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table VISITOR
--------------------------------------------------------

  ALTER TABLE "HBM"."VISITOR" ADD CONSTRAINT "VISITOR_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HBM"."VISITOR" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("BIRTH" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("NO" NOT NULL ENABLE);
