OPTIONS (ERRORS=50)
LOAD DATA 
INFILE '/home/hoon/Workspace_Java/HBM/sql/VISITOR_DETAIL_DATA_TABLE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "HBM"."VISITOR_DETAIL"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"VNO" ,
"IMGFILENAME" CHAR (60),
L_0 FILLER char,
"IMGFILECONT" LOBFILE( L_0) TERMINATED BY EOF NULLIF L_0 = 'null',
"HPHONE" CHAR (10),
"ADDR" CHAR (100),
"COMP" CHAR (60),
"POS" CHAR (40))
