--------------------------------------------------------
--  파일이 생성됨 - 목요일-1월-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VISITOR
--------------------------------------------------------

  CREATE TABLE "HBM"."VISITOR" 
   (	"NO" NUMBER, 
	"GRADE" NUMBER(1,0), 
	"ID" VARCHAR2(40 BYTE), 
	"PW" VARCHAR2(60 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"BIRTH" DATE, 
	"EMAIL" VARCHAR2(60 BYTE), 
	"PHONE" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HBM.VISITOR
SET DEFINE OFF;
Insert into HBM.VISITOR (NO,GRADE,ID,PW,LNAME,FNAME,BIRTH,EMAIL,PHONE) values (98,3,'joen76191','asdasd1!','Jeon','YangHoon',to_date('18/01/03','RR/MM/DD'),'joen7619@naver.com','012345678');
Insert into HBM.VISITOR (NO,GRADE,ID,PW,LNAME,FNAME,BIRTH,EMAIL,PHONE) values (99,3,'joen76192','asdasd1!','Jeon','YangHoon',to_date('18/01/04','RR/MM/DD'),'joen7619@naver.com','01234567');
Insert into HBM.VISITOR (NO,GRADE,ID,PW,LNAME,FNAME,BIRTH,EMAIL,PHONE) values (101,3,'joen76194','asdasd1!','Jeon','YangHoon',to_date('18/01/10','RR/MM/DD'),'joen7619@naver.com','012345678');
Insert into HBM.VISITOR (NO,GRADE,ID,PW,LNAME,FNAME,BIRTH,EMAIL,PHONE) values (100,3,'joen76193','asdasd1!','Jeon','YangHoon',to_date('18/01/12','RR/MM/DD'),'joen7619@naver.com','012345678');
--------------------------------------------------------
--  DDL for Index VISITOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HBM"."VISITOR_PK" ON "HBM"."VISITOR" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VISITOR_UK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HBM"."VISITOR_UK_ID" ON "HBM"."VISITOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table VISITOR
--------------------------------------------------------

  ALTER TABLE "HBM"."VISITOR" ADD CONSTRAINT "VISITOR_UK_ID" UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HBM"."VISITOR" ADD CONSTRAINT "VISITOR_CHK_GRADE" CHECK (GRADE >= 0 AND GRADE <= 9) ENABLE;
  ALTER TABLE "HBM"."VISITOR" ADD CONSTRAINT "VISITOR_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HBM"."VISITOR" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("BIRTH" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "HBM"."VISITOR" MODIFY ("NO" NOT NULL ENABLE);
