--------------------------------------------------------
--  DDL for Table VISITOR
--------------------------------------------------------

  CREATE TABLE "HBM"."VISITOR" 
   (	"NO" NUMBER, 
	"GRADE" NUMBER(1,0), 
	"ID" VARCHAR2(40 BYTE), 
	"PW" VARCHAR2(60 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"BIRTH" DATE, 
	"EMAIL" VARCHAR2(60 BYTE), 
	"PHONE" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
